// app/data/accessoriesData.tsx

const accessoriesData = [
  {
    image: "/honda-civic-2019.png",
    title: "Alloy Wheels",
    sub_title: "Premium Rims",
    feature1: "Set of 4",
    feature2: "18 inch",
    feature3: "Matte Black",
    price: "Starting from",
    amount_price: "$800",
    sub_price: "$1,000",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Leather Seat Covers",
    sub_title: "Luxury Feel",
    feature1: "Waterproof",
    feature2: "Universal Fit",
    feature3: "Black & Red",
    price: "Starting from",
    amount_price: "$150",
    sub_price: "$200",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Car Audio Speakers",
    sub_title: "High Bass Sound",
    feature1: "4 Speakers",
    feature2: "Bluetooth",
    feature3: "1200W Power",
    price: "Starting from",
    amount_price: "$350",
    sub_price: "$400",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Car Air Freshener",
    sub_title: "Luxury Perfume",
    feature1: "Long Lasting",
    feature2: "Ocean Scent",
    feature3: "Compact Design",
    price: "Starting from",
    amount_price: "$20",
    sub_price: "$30",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Steering Wheel Cover",
    sub_title: "Grip & Comfort",
    feature1: "Leather Finish",
    feature2: "Universal Fit",
    feature3: "Anti-Slip",
    price: "Starting from",
    amount_price: "$40",
    sub_price: "$60",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Car Floor Mats",
    sub_title: "Durable Rubber",
    feature1: "Set of 5",
    feature2: "Dust Proof",
    feature3: "Easy Washable",
    price: "Starting from",
    amount_price: "$70",
    sub_price: "$90",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Dashboard Camera",
    sub_title: "HD Recording",
    feature1: "Night Vision",
    feature2: "Loop Recording",
    feature3: "Wide Angle Lens",
    price: "Starting from",
    amount_price: "$120",
    sub_price: "$150",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Car Body Cover",
    sub_title: "All Weather Protection",
    feature1: "Waterproof",
    feature2: "Dust Resistant",
    feature3: "Universal Size",
    price: "Starting from",
    amount_price: "$90",
    sub_price: "$120",
  },
  {
    image: "/honda-civic-2019.png",
    title: "GPS Navigation System",
    sub_title: "Smart Display",
    feature1: "Voice Commands",
    feature2: "Touch Screen",
    feature3: "Real Time Traffic",
    price: "Starting from",
    amount_price: "$300",
    sub_price: "$350",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Portable Car Vacuum",
    sub_title: "Compact Cleaner",
    feature1: "Rechargeable",
    feature2: "High Suction",
    feature3: "Lightweight",
    price: "Starting from",
    amount_price: "$60",
    sub_price: "$80",
  },
  {
    image: "/honda-civic-2019.png",
    title: "LED Headlights",
    sub_title: "Bright & Clear",
    feature1: "6000K White",
    feature2: "Energy Efficient",
    feature3: "Plug & Play",
    price: "Starting from",
    amount_price: "$180",
    sub_price: "$220",
  },
  {
    image: "/honda-civic-2019.png",
    title: "Car Battery Charger",
    sub_title: "Fast Charging",
    feature1: "12V/24V Support",
    feature2: "Overcharge Protection",
    feature3: "Portable Design",
    price: "Starting from",
    amount_price: "$100",
    sub_price: "$130",
  },
];

export default accessoriesData;
