// app/HomePage/carsData.ts
export interface Car {
  image: string;
  title: string;
  sub_title: string;
  num: number;
  num2: string;
  num3: string;
  price: string;
  amount_price: string;
  sub_price: string;
}

export const carsData: Car[] = [
  {
    image: "/toyota-camry-2020.png",
    title: "Tesla Model S",
    sub_title: "Electric Sedan",
    num: 5,
    num2: "Electric",
    num3: "250 km/h",
    price: "Starting from",
    amount_price: "$80,000",
    sub_price: "$90,000",
  },
  {
    image: "/toyota-camry-2020.png",
    title: "BMW X5",
    sub_title: "Luxury SUV",
    num: 7,
    num2: "Petrol",
    num3: "240 km/h",
    price: "Starting from",
    amount_price: "$70,000",
    sub_price: "$85,000",
  },
  {
    image: "/toyota-camry-2020.png",
    title: "Range Rover Evoque",
    sub_title: "Offroad Beast",
    num: 5,
    num2: "Diesel",
    num3: "220 km/h",
    price: "Starting from",
    amount_price: "$90,000",
    sub_price: "$100,000",
  },
  {
    image: "/toyota-camry-2020.png",
    title: "Ferrari 488",
    sub_title: "Sports Car",
    num: 2,
    num2: "Petrol",
    num3: "330 km/h",
    price: "Starting from",
    amount_price: "$250,000",
    sub_price: "$280,000",
  },
  {
    image: "/toyota-camry-2020.png",
    title: "Audi A8",
    sub_title: "Executive Sedan",
    num: 5,
    num2: "Hybrid",
    num3: "260 km/h",
    price: "Starting from",
    amount_price: "$95,000",
    sub_price: "$110,000",
  },
  {
    image: "/toyota-camry-2020.png",
    title: "Lamborghini Huracan",
    sub_title: "Supercar",
    num: 2,
    num2: "Petrol",
    num3: "340 km/h",
    price: "Starting from",
    amount_price: "$300,000",
    sub_price: "$330,000",
  },
  {
    image: "/toyota-camry-2020.png",
    title: "Mercedes G-Wagon",
    sub_title: "Luxury SUV",
    num: 7,
    num2: "Diesel",
    num3: "210 km/h",
    price: "Starting from",
    amount_price: "$150,000",
    sub_price: "$170,000",
  },
  {
    image: "/toyota-camry-2020.png",
    title: "Porsche 911",
    sub_title: "Iconic Coupe",
    num: 4,
    num2: "Petrol",
    num3: "320 km/h",
    price: "Starting from",
    amount_price: "$200,000",
    sub_price: "$230,000",
  },
  {
    image: "/toyota-camry-2020.png",
    title: "Toyota Supra",
    sub_title: "JDM Legend",
    num: 2,
    num2: "Petrol",
    num3: "280 km/h",
    price: "Starting from",
    amount_price: "$60,000",
    sub_price: "$75,000",
  },
  {
    image: "/toyota-camry-2020.png",
    title: "Nissan GTR",
    sub_title: "Godzilla",
    num: 4,
    num2: "Petrol",
    num3: "310 km/h",
    price: "Starting from",
    amount_price: "$120,000",
    sub_price: "$135,000",
  },
  {
    image: "/toyota-camry-2020.png",
    title: "Bugatti Chiron",
    sub_title: "Fastest Car",
    num: 2,
    num2: "Petrol",
    num3: "420 km/h",
    price: "Starting from",
    amount_price: "$3,000,000",
    sub_price: "$3,300,000",
  },
  {
    image: "/toyota-camry-2020.png",
    title: "Ford Mustang",
    sub_title: "American Muscle",
    num: 4,
    num2: "Petrol",
    num3: "260 km/h",
    price: "Starting from",
    amount_price: "$55,000",
    sub_price: "$70,000",
  },
];
